<#
  Helix - testnet deploy + initialize + seed.

  Deploys all 6 contracts to Stellar testnet, wires the cross-contract addresses,
  sets roles, lists the XAU/EUR/XLM markets, seeds LP liquidity + demo positions,
  and writes the resulting addresses to deploy/testnet.json + web/.env.local.

  Prereqs: stellar-cli v25.2+ on PATH, a funded identity (default alias "helix").
  Usage:   pwsh scripts/deploy_testnet.ps1 [-Key helix] [-Network testnet]
#>
param(
  [string]$Key = "helix",
  [string]$Network = "testnet"
)
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root
$env:Path = "$env:USERPROFILE\.cargo\bin;$env:Path"

$WASM = "target/wasm32v1-none/release"
$tmp = Join-Path ([System.IO.Path]::GetTempPath()) "helix-deploy"
New-Item -ItemType Directory -Force -Path $tmp | Out-Null
New-Item -ItemType Directory -Force -Path "$root/deploy" | Out-Null

function St { param([Parameter(ValueFromRemainingArguments=$true)][string[]]$a)
  $out = & stellar @a
  if ($LASTEXITCODE -ne 0) { throw "stellar $($a -join ' ') failed (exit $LASTEXITCODE)" }
  return ($out | Out-String).Trim()
}
function CID { param([string]$s)
  $m = [regex]::Match($s, 'C[A-Z2-7]{55}')
  if (-not $m.Success) { throw "no contract id in: $s" }
  return $m.Value
}
function Deploy { param([string]$name, [string[]]$ctorArgs)
  Write-Host "  deploying $name ..." -ForegroundColor Cyan
  $out = St contract deploy --wasm "$WASM/$name.wasm" --source $Key --network $Network '--' @ctorArgs
  $id = CID $out
  Write-Host "    $name = $id" -ForegroundColor Green
  return $id
}
function Json { param([string]$obj, [string]$file)
  $p = Join-Path $tmp $file
  [System.IO.File]::WriteAllText($p, $obj)
  return $p
}

$ADMIN = St keys address $Key
Write-Host "Admin/Keeper: $ADMIN" -ForegroundColor Yellow

# --- 1. Deploy ------------------------------------------------------------
$USDC   = Deploy "mock_usdc"       @("--name", "Helix USD", "--symbol", "USDC", "--admin", $ADMIN, "--initial_supply", "0")
$ORACLE = Deploy "mock_oracle"     @("--admin", $ADMIN, "--decimals", "14")
$ADAPTER= Deploy "oracle_adapter"  @("--admin", $ADMIN, "--reflector", $ORACLE, "--max_age", "3600", "--max_deviation_bps", "2000")
$REG    = Deploy "market_registry" @("--admin", $ADMIN, "--keeper", $ADMIN)
$VAULT  = Deploy "collateral_vault"@("--admin", $ADMIN, "--token", $USDC)
$ENGINE = Deploy "perp_engine"     @("--registry", $REG, "--oracle", $ADAPTER, "--vault", $VAULT)

function Write-Outputs { param([string]$txHash = "")
  $expert = "https://stellar.expert/explorer/testnet/contract"
  $txLink = ""
  if ($txHash) { $txLink = "https://stellar.expert/explorer/testnet/tx/$txHash" }
  $out = [ordered]@{
    network = $Network; admin = $ADMIN; keeper = $ADMIN
    deployed_at = (Get-Date).ToUniversalTime().ToString("o"); latest_tx = $txHash
    contracts = [ordered]@{
      mock_usdc=$USDC; mock_oracle=$ORACLE; oracle_adapter=$ADAPTER
      market_registry=$REG; collateral_vault=$VAULT; perp_engine=$ENGINE
    }
    explorer = [ordered]@{
      mock_usdc="$expert/$USDC"; oracle_adapter="$expert/$ADAPTER"; market_registry="$expert/$REG"
      collateral_vault="$expert/$VAULT"; perp_engine="$expert/$ENGINE"
      latest_tx = $txLink
    }
  }
  $json = $out | ConvertTo-Json -Depth 6
  [System.IO.File]::WriteAllText("$root/deploy/testnet.json", $json)
  $envLines = @(
    "# Auto-generated by scripts/deploy_testnet.ps1 - $(Get-Date -Format o)"
    "NEXT_PUBLIC_STELLAR_NETWORK=$Network"
    "NEXT_PUBLIC_RPC_URL=https://soroban-testnet.stellar.org"
    "NEXT_PUBLIC_NETWORK_PASSPHRASE=Test SDF Network ; September 2015"
    "NEXT_PUBLIC_HORIZON_URL=https://horizon-testnet.stellar.org"
    "NEXT_PUBLIC_MOCK_USDC_ID=$USDC"
    "NEXT_PUBLIC_MOCK_ORACLE_ID=$ORACLE"
    "NEXT_PUBLIC_ORACLE_ADAPTER_ID=$ADAPTER"
    "NEXT_PUBLIC_MARKET_REGISTRY_ID=$REG"
    "NEXT_PUBLIC_COLLATERAL_VAULT_ID=$VAULT"
    "NEXT_PUBLIC_PERP_ENGINE_ID=$ENGINE"
  )
  New-Item -ItemType Directory -Force -Path "$root/web" | Out-Null
  [System.IO.File]::WriteAllText("$root/web/.env.local", ($envLines -join "`n"))
  return $json
}

# --- 2. Wire --------------------------------------------------------------
Write-Host "Wiring vault -> engine ..." -ForegroundColor Cyan
St contract invoke --id $VAULT --source $Key --network $Network '--' set_engine --engine $ENGINE | Out-Null
Write-Outputs | Out-Null   # persist addresses immediately, before seeding

# Feeds: protocol feed key -> Reflector asset selector.
$markets = @(
  @{ id=1; sym="XAUPERP"; feed="XAU"; price="240000000000000000"; lev=20; imr=500;  mmr=250; taker=10; liq=100; fund=100 }
  @{ id=2; sym="EURPERP"; feed="EUR"; price="108000000000000";    lev=25; imr=400;  mmr=200; taker=8;  liq=80;  fund=80  }
  @{ id=3; sym="XLMPERP"; feed="XLM"; price="12000000000000";     lev=10; imr=1000; mmr=500; taker=12; liq=120; fund=120 }
)

foreach ($m in $markets) {
  Write-Host "Listing market $($m.sym) ..." -ForegroundColor Cyan
  $asset = Json ('{"Other":"' + $m.feed + '"}') "asset_$($m.feed).json"
  St contract invoke --id $ADAPTER --source $Key --network $Network '--' set_feed --feed $m.feed --asset-file-path $asset | Out-Null
  St contract invoke --id $ORACLE  --source $Key --network $Network '--' set_price --asset-file-path $asset --price $m.price | Out-Null
  $cfg = @{
    id=$m.id; symbol=$m.sym; feed=$m.feed; max_leverage=$m.lev; imr_bps=$m.imr; mmr_bps=$m.mmr;
    taker_fee_bps=$m.taker; liquidation_fee_bps=$m.liq; max_oi="10000000000000";
    min_position_size="100000000"; max_funding_rate_bps=$m.fund; paused=$false
  } | ConvertTo-Json -Compress
  $cfgFile = Json $cfg "market_$($m.id).json"
  St contract invoke --id $REG --source $Key --network $Network '--' add_market --cfg-file-path $cfgFile | Out-Null
}

# --- 3. Seed (non-fatal: addresses already persisted) ---------------------
Write-Host "Seeding USDC + LP liquidity ..." -ForegroundColor Cyan
St contract invoke --id $USDC  --source $Key --network $Network '--' faucet --to $ADMIN --amount "7000000000000" | Out-Null   # 700k USDC
St contract invoke --id $VAULT --source $Key --network $Network '--' add_liquidity --from $ADMIN --amount "5000000000000" | Out-Null # 500k LP

Write-Host "Opening demo positions ..." -ForegroundColor Cyan
try {
  # XAU 5x long: margin 2,000 notional 10,000
  St contract invoke --id $ENGINE --source $Key --network $Network '--' open_position --trader $ADMIN --market_id 1 --side Long --margin "20000000000" --notional "100000000000" --ref_price 0 --max_slippage_bps 0 | Out-Null
  # EUR 4x short: margin 1,500 notional 6,000
  St contract invoke --id $ENGINE --source $Key --network $Network '--' open_position --trader $ADMIN --market_id 2 --side Short --margin "15000000000" --notional "60000000000" --ref_price 0 --max_slippage_bps 0 | Out-Null
} catch { Write-Host "  (demo position seeding skipped: $_)" -ForegroundColor DarkYellow }

Write-Host "Bootstrapping funding ..." -ForegroundColor Cyan
foreach ($m in $markets) {
  try { St contract invoke --id $ENGINE --source $Key --network $Network '--' update_funding --keeper $ADMIN --market_id $m.id | Out-Null }
  catch { Write-Host "  (funding update for $($m.sym) skipped: $_)" -ForegroundColor DarkYellow }
}

# --- 4. Capture a real tx hash + rewrite outputs --------------------------
$txHash = ""
try {
  $resp = Invoke-RestMethod -Uri "https://horizon-testnet.stellar.org/accounts/$ADMIN/transactions?order=desc&limit=1" -TimeoutSec 20
  $txHash = $resp._embedded.records[0].hash
} catch { Write-Host "  (could not fetch latest tx hash: $_)" -ForegroundColor DarkYellow }

$json = Write-Outputs -txHash $txHash
Write-Host "`nDeploy complete." -ForegroundColor Green
Write-Host $json
